server:
    image: nginx:mainline-alpine
    container_name: container_server
    ports:
        - "80:80"
    volumes:
        - ./site.conf:/etc/nginx/conf.d/site.conf
        - ./src:/var/www/html/src
    links:
        - php

php:
    build: .
    container_name: container_php
    volumes:
        - ./src:/var/www/html/src
